LOG_FILE_NAME = "log.txt"
LOG_FORMAT = "%(asctime)s %(levelname)s: %(message)s"
SAT_DATA_URL = "https://services.swpc.noaa.gov/json/ovation_aurora_latest.json"
UNIX_APP_DATA_PATH = "~/.auroaexplorer"
WIN_APP_DATA_PATH = "%APPDATA%"